### ISSUE TITLE
Let reevaluate option take paths

### ISSUE THREAD

**Issue by nodejsjs** [ismaeldivita/change-tracker-plugin#11]
Sometimes there are `buildsystem`, `config` or `buildSrc` directories (not modules) that contains dependency versions for all libs. Changes in them should behave like the `reevaluate` option. Having module names in `reevaluate` is great but it'd be awesome if we can also include paths there as well.

Something like this https://github.com/dropbox/AffectedModuleDetector#installation

```
reevaluate = ["config/", ":core", ":sharedTest"]
```

They could be different options as well

**Comment by ismaeldivita** [comment]
This should be working without any additional configuration.

If you change something and we could not find the project (module) for this file, the plugin will automatic trigger the tasks for all modules. So, for your case, any change on `config/` should be triggering tasks for all modules.

This is not working for you?

**Comment by nodejsjs** [comment]
I've just tested this by changing non-module files and it indeed works. Thanks for the great plugin!

**Comment by ismaeldivita** [comment]
I'll update the README file about it. This behavior is not too clear when you read the documentation.
