### ISSUE TITLE
Logging diffs

### ISSUE THREAD

**Issue by mshearer123** [ismaeldivita/change-tracker-plugin#6]
Hi,

No rush at all, but if you do another release, do you think it would be possible to add more logging for the diffs found?
We're having trouble identifying what is changing in our root gradle in CI

cheers

**Comment by ismaeldivita** [comment]
You mean log the actual changes? Not sure if it's a good idea, may pollute too much the log.

You can debug this by simply using git diffs.
Just remember the plugin use merge base diffs by default, so use three dots `git diff A...B`

Also, double check how your CI is cloning the repo and forks, and if you setup the remote on the plugin

**Comment by mshearer123** [comment]
thanks @ismaeldivita I'll try that
